### ISSUE TITLE
Update on a newly created resource group cannot be saved.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#12]
Repro Steps:
1. New a resource group "leila01".
2. Next, modify "leila01" to delete its description and click save button. However, the save and cancel button and are still enabled which is wrong. The update is not actually saved and you can see the description for the resource group after reopening the form.

**Comment by 929lwang1** [comment]
Cannot recreate this issue.
Need to review this together with Leila.

**Comment by 929lwang1** [comment]
This is fixed under commit 15421afd09f35d68e429a4d14c75e3e6c0bc744d and then commit a517c857ca3c635bf49613e4c303b5dfcc5b670e, with exe file committed under commit 53554889ae7e1497c437de0081d8c990691df767.
Tested locally with above steps. The update process can work properly.
Please review and let me know if there's any question. Thanks.

**Comment by LeilaWang2** [comment]
Issue still exists with 20190423-1716
Launch resource group and created a new resource group “Bubble". Continue to update the resource group and click save button, the save button is still enabled and change is not saved.
![image](https://user-images.githubusercontent.com/49714253/56572669-19272e80-65f2-11e9-8beb-ea02a51eb7f5.png)

**Comment by 929lwang1** [comment]
Fixed it under commit 3ebd3a7cb70eab034a64b59b8138dada8807ee0b.
The key step to recreate this issue is to leave the four Time fields AS IS in new mode, and then edit the newly created record.
Tested locally. Now the New -> Save -> Update -> Save works properly.
Please review and let me know if there's any question. Thanks.

**Comment by LeilaWang2** [comment]
Issue was fixed in 20190424-1754.
